version: '3.6'
services: 

  db:
    image: postgres:latest
    container_name: postgre-user
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: startup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deb.deb
      POSTGRES_DATABASE: startup
    networks: 
      - server-side

  user:
    build:
      context: ./user
    ports:
      - "4001:4001"
    networks: 
      - server-side
      - gateway-side
    depends_on:
      - db

  reward:
    build:
      context: ./reward
    ports:
      - "4002:4002"
    networks: 
      - server-side
      - gateway-side
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
    ports:
      - "4000:4000"
    networks: 
      - gateway-side
    depends_on:
      - user
      - reward

networks: 
  server-side:
  gateway-side:
